require("oquinena.config")
require("oquinena.keymap")
require("oquinena.packer")
require("oquinena.lualine")
require("oquinena.buffer_manager")
require("oquinena.file_browser")
require("oquinena.mason-null-ls")
-- require("oquinena.ufo")
-- require("oquinena.tabnine")
